### ISSUE TITLE
Last build not working in dsimenu++

### ISSUE THREAD

**Issue by Valkristh** [ApacheThunder/NesDS#1]
Hello, like the title said, build 1.3d it's give a red screen in the bottom with the text "guru meditation error" and some numbers
The console is a DSi
The previous build is working fine without the touchscreen, but i managed to edit settings for shortcuts with the buttons

**Comment by ApacheThunder** [comment]
I don't have any plans to update this to work in DSiMenu++. Mainly because I don't use that to load homebrew and I don't want to go through the trouble of trying to make it work right on both DSiMenu++ and System Menu.

I have it installed directly to System Menu. I'm not sure why the touch screen isn't working though. I am not actively working on this right now.

**Comment by Valkristh** [comment]
Oh ok

**Comment by ApacheThunder** [comment]
Ok so I had time to look at this. I think I know why. Because of the last commit, this no longer works in NTR mode. DSiMenu++ assumes this is NTR mode homebrew so it's probably trying to boot it in NTR mode. This is more of an issue for DSiMenu++ so you need to open an issue for them telling them to check for the TWL mode bit in the NTR header and load it in TWL mode instead. (it will have to parse the DSI Extended header among other things unless they use System Menu to do the work instead via autoboot)
